-- ZIPPO Marketplace Expansion (roles + gifts marketplace workflows)
-- Date: 2026-05-08

BEGIN;

CREATE SCHEMA IF NOT EXISTS zippo;

CREATE OR REPLACE FUNCTION zippo.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT
    (auth.jwt()->'app_metadata'->>'role' = 'admin')
    OR (auth.jwt()->'user_metadata'->>'role' = 'admin')
    OR (COALESCE(LOWER(auth.jwt()->'app_metadata'->>'is_admin'), '') = 'true')
    OR (COALESCE(LOWER(auth.jwt()->'user_metadata'->>'is_admin'), '') = 'true');
$$;

CREATE OR REPLACE FUNCTION zippo.jwt_role()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    auth.jwt()->'app_metadata'->>'role',
    auth.jwt()->'user_metadata'->>'role',
    'guest'
  );
$$;

CREATE TABLE IF NOT EXISTS zippo.marketplace_profiles (
  profile_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid,
  user_id bigint UNIQUE,
  role text NOT NULL DEFAULT 'buyer' CHECK (role IN ('buyer', 'store_owner', 'driver', 'admin')),
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  barangay text,
  address_line text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.store_owner_applications (
  application_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_user_id bigint NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  contact_no text NOT NULL,
  bir_tin text NOT NULL,
  dti_registration_no text NOT NULL,
  business_name text NOT NULL,
  business_address text NOT NULL,
  barangay text NOT NULL,
  documents jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'approved', 'rejected')),
  moderation_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.stores (
  store_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id bigint NOT NULL,
  store_name text NOT NULL,
  description text,
  barangay text NOT NULL,
  lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
  lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.marketplace_products (
  product_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id bigint NOT NULL REFERENCES zippo.stores(store_id) ON DELETE CASCADE,
  owner_user_id bigint NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'gift',
  price numeric(10, 2) NOT NULL CHECK (price >= 0),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  occasion_tags text[] NOT NULL DEFAULT '{}'::text[],
  recipient_tags text[] NOT NULL DEFAULT '{}'::text[],
  tags text[] NOT NULL DEFAULT '{}'::text[],
  delivery_zones text[] NOT NULL DEFAULT '{}'::text[],
  local_vendor boolean NOT NULL DEFAULT true,
  avg_rating numeric(2, 1) CHECK (avg_rating IS NULL OR avg_rating BETWEEN 1.0 AND 5.0),
  popularity_score double precision NOT NULL DEFAULT 0 CHECK (popularity_score BETWEEN 0 AND 1),
  store_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.buyer_orders (
  order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_user_id bigint NOT NULL,
  occasion text NOT NULL,
  recipient_type text NOT NULL,
  notes text,
  gift_pack jsonb NOT NULL DEFAULT '{}'::jsonb,
  delivery jsonb NOT NULL DEFAULT '{}'::jsonb,
  subtotal numeric(10, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  gift_pack_fee numeric(10, 2) NOT NULL DEFAULT 0 CHECK (gift_pack_fee >= 0),
  delivery_fee numeric(10, 2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
  total_price numeric(10, 2) NOT NULL DEFAULT 0 CHECK (total_price >= 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'processing', 'ready_for_pickup', 'in_transit', 'delivered', 'cancelled', 'refunded')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.buyer_order_items (
  order_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES zippo.buyer_orders(order_id) ON DELETE CASCADE,
  product_id bigint,
  name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(10, 2) NOT NULL CHECK (unit_price >= 0),
  line_total numeric(10, 2) NOT NULL CHECK (line_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.fraud_reports (
  report_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_user_id bigint NOT NULL,
  accused_role text NOT NULL CHECK (accused_role IN ('buyer', 'store_owner', 'driver')),
  accused_user_id bigint,
  accused_store_id bigint,
  reason text NOT NULL,
  details text,
  evidence_url text,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'resolved', 'dismissed')),
  moderation_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.driver_tasks (
  task_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_user_id bigint NOT NULL,
  order_id bigint,
  pickup_label text,
  dropoff_label text,
  status text NOT NULL DEFAULT 'assigned' CHECK (status IN ('assigned', 'picked_up', 'in_transit', 'delivered', 'failed', 'cancelled')),
  last_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE zippo.marketplace_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.store_owner_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.marketplace_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.buyer_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.buyer_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.fraud_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.driver_tasks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS marketplace_profiles_self_read ON zippo.marketplace_profiles;
CREATE POLICY marketplace_profiles_self_read
ON zippo.marketplace_profiles FOR SELECT TO authenticated
USING (
  zippo.is_admin()
  OR (auth.uid() IS NOT NULL AND auth.uid() = auth_user_id)
);

DROP POLICY IF EXISTS marketplace_profiles_self_write ON zippo.marketplace_profiles;
CREATE POLICY marketplace_profiles_self_write
ON zippo.marketplace_profiles FOR ALL TO authenticated
USING (
  zippo.is_admin()
  OR (auth.uid() IS NOT NULL AND auth.uid() = auth_user_id)
)
WITH CHECK (
  zippo.is_admin()
  OR (auth.uid() IS NOT NULL AND auth.uid() = auth_user_id)
);

DROP POLICY IF EXISTS stores_public_read ON zippo.stores;
CREATE POLICY stores_public_read
ON zippo.stores FOR SELECT TO anon, authenticated
USING (is_active = true OR zippo.is_admin());

DROP POLICY IF EXISTS stores_owner_write ON zippo.stores;
CREATE POLICY stores_owner_write
ON zippo.stores FOR ALL TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'store_owner')
WITH CHECK (zippo.is_admin() OR zippo.jwt_role() = 'store_owner');

DROP POLICY IF EXISTS products_public_read ON zippo.marketplace_products;
CREATE POLICY products_public_read
ON zippo.marketplace_products FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS products_owner_write ON zippo.marketplace_products;
CREATE POLICY products_owner_write
ON zippo.marketplace_products FOR ALL TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'store_owner')
WITH CHECK (zippo.is_admin() OR zippo.jwt_role() = 'store_owner');

DROP POLICY IF EXISTS buyer_orders_self_read ON zippo.buyer_orders;
CREATE POLICY buyer_orders_self_read
ON zippo.buyer_orders FOR SELECT TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'buyer');

DROP POLICY IF EXISTS buyer_orders_self_write ON zippo.buyer_orders;
CREATE POLICY buyer_orders_self_write
ON zippo.buyer_orders FOR ALL TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'buyer')
WITH CHECK (zippo.is_admin() OR zippo.jwt_role() = 'buyer');

DROP POLICY IF EXISTS buyer_order_items_read ON zippo.buyer_order_items;
CREATE POLICY buyer_order_items_read
ON zippo.buyer_order_items FOR SELECT TO authenticated
USING (
  zippo.is_admin()
  OR EXISTS (
    SELECT 1
    FROM zippo.buyer_orders bo
    WHERE bo.order_id = buyer_order_items.order_id
      AND zippo.jwt_role() = 'buyer'
  )
);

DROP POLICY IF EXISTS buyer_order_items_write ON zippo.buyer_order_items;
CREATE POLICY buyer_order_items_write
ON zippo.buyer_order_items FOR INSERT TO authenticated
WITH CHECK (zippo.is_admin() OR zippo.jwt_role() = 'buyer');

DROP POLICY IF EXISTS reports_self_create ON zippo.fraud_reports;
CREATE POLICY reports_self_create
ON zippo.fraud_reports FOR INSERT TO authenticated
WITH CHECK (zippo.jwt_role() IN ('buyer', 'store_owner', 'driver', 'admin'));

DROP POLICY IF EXISTS reports_read_scope ON zippo.fraud_reports;
CREATE POLICY reports_read_scope
ON zippo.fraud_reports FOR SELECT TO authenticated
USING (zippo.is_admin() OR reporter_user_id IS NOT NULL);

DROP POLICY IF EXISTS reports_admin_moderate ON zippo.fraud_reports;
CREATE POLICY reports_admin_moderate
ON zippo.fraud_reports FOR UPDATE TO authenticated
USING (zippo.is_admin())
WITH CHECK (zippo.is_admin());

DROP POLICY IF EXISTS driver_tasks_driver_read ON zippo.driver_tasks;
CREATE POLICY driver_tasks_driver_read
ON zippo.driver_tasks FOR SELECT TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'driver');

DROP POLICY IF EXISTS driver_tasks_driver_update ON zippo.driver_tasks;
CREATE POLICY driver_tasks_driver_update
ON zippo.driver_tasks FOR UPDATE TO authenticated
USING (zippo.is_admin() OR zippo.jwt_role() = 'driver')
WITH CHECK (zippo.is_admin() OR zippo.jwt_role() = 'driver');

DROP POLICY IF EXISTS driver_tasks_admin_insert ON zippo.driver_tasks;
CREATE POLICY driver_tasks_admin_insert
ON zippo.driver_tasks FOR INSERT TO authenticated
WITH CHECK (zippo.is_admin());

DROP POLICY IF EXISTS applications_create ON zippo.store_owner_applications;
CREATE POLICY applications_create
ON zippo.store_owner_applications FOR INSERT TO authenticated
WITH CHECK (zippo.jwt_role() IN ('buyer', 'store_owner', 'admin'));

DROP POLICY IF EXISTS applications_read_scope ON zippo.store_owner_applications;
CREATE POLICY applications_read_scope
ON zippo.store_owner_applications FOR SELECT TO authenticated
USING (zippo.is_admin() OR applicant_user_id IS NOT NULL);

DROP POLICY IF EXISTS applications_admin_update ON zippo.store_owner_applications;
CREATE POLICY applications_admin_update
ON zippo.store_owner_applications FOR UPDATE TO authenticated
USING (zippo.is_admin())
WITH CHECK (zippo.is_admin());

DROP TRIGGER IF EXISTS trg_marketplace_profiles_updated_at ON zippo.marketplace_profiles;
CREATE TRIGGER trg_marketplace_profiles_updated_at
BEFORE UPDATE ON zippo.marketplace_profiles
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_store_owner_applications_updated_at ON zippo.store_owner_applications;
CREATE TRIGGER trg_store_owner_applications_updated_at
BEFORE UPDATE ON zippo.store_owner_applications
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_stores_updated_at ON zippo.stores;
CREATE TRIGGER trg_stores_updated_at
BEFORE UPDATE ON zippo.stores
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_marketplace_products_updated_at ON zippo.marketplace_products;
CREATE TRIGGER trg_marketplace_products_updated_at
BEFORE UPDATE ON zippo.marketplace_products
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_buyer_orders_updated_at ON zippo.buyer_orders;
CREATE TRIGGER trg_buyer_orders_updated_at
BEFORE UPDATE ON zippo.buyer_orders
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_fraud_reports_updated_at ON zippo.fraud_reports;
CREATE TRIGGER trg_fraud_reports_updated_at
BEFORE UPDATE ON zippo.fraud_reports
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_driver_tasks_updated_at ON zippo.driver_tasks;
CREATE TRIGGER trg_driver_tasks_updated_at
BEFORE UPDATE ON zippo.driver_tasks
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_marketplace_profiles_role ON zippo.marketplace_profiles(role);
CREATE INDEX IF NOT EXISTS idx_store_owner_applications_status ON zippo.store_owner_applications(status);
CREATE INDEX IF NOT EXISTS idx_stores_owner ON zippo.stores(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_marketplace_products_store_id ON zippo.marketplace_products(store_id);
CREATE INDEX IF NOT EXISTS idx_marketplace_products_tags ON zippo.marketplace_products USING gin(tags);
CREATE INDEX IF NOT EXISTS idx_marketplace_products_occasion_tags ON zippo.marketplace_products USING gin(occasion_tags);
CREATE INDEX IF NOT EXISTS idx_marketplace_products_recipient_tags ON zippo.marketplace_products USING gin(recipient_tags);
CREATE INDEX IF NOT EXISTS idx_buyer_orders_buyer ON zippo.buyer_orders(buyer_user_id);
CREATE INDEX IF NOT EXISTS idx_buyer_orders_status ON zippo.buyer_orders(status);
CREATE INDEX IF NOT EXISTS idx_fraud_reports_status ON zippo.fraud_reports(status);
CREATE INDEX IF NOT EXISTS idx_driver_tasks_driver_user ON zippo.driver_tasks(driver_user_id);
CREATE INDEX IF NOT EXISTS idx_driver_tasks_status ON zippo.driver_tasks(status);

COMMIT;
