-- ZIPPO Intelligent Systems - PostgreSQL/Supabase Schema
-- DDL only. No generated data / seed INSERT statements are included.
-- Intended for Supabase SQL Editor.

BEGIN;

CREATE SCHEMA IF NOT EXISTS zippo;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- ENUM TYPES
-- =========================

DO $$ BEGIN
    CREATE TYPE zippo.age_group AS ENUM ('18-25', '26-35', '36-50');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.gender_code AS ENUM ('M', 'F');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.budget_range AS ENUM ('low', 'mid', 'high');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.product_category AS ENUM ('food', 'hamper', 'craft');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.order_status AS ENUM ('pending', 'paid', 'processing', 'completed', 'cancelled', 'refunded');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.delivery_status AS ENUM ('pending', 'assigned', 'in_transit', 'delivered', 'failed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.delivery_time_slot AS ENUM ('Morning', 'PM', 'Eve');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.route_stop_action AS ENUM ('pickup', 'dropoff');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE zippo.assignment_status AS ENUM ('assigned', 'unassigned', 'completed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =========================
-- UTILITY TRIGGER
-- =========================

CREATE OR REPLACE FUNCTION zippo.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- =========================
-- CORE TABLES FROM DATABASE SCHEMA PDF
-- =========================

-- Optional normalization table for local vendors.
-- products.vendor_name is still kept because the original products.csv schema includes it.
CREATE TABLE IF NOT EXISTS zippo.vendors (
    vendor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_name text NOT NULL UNIQUE,
    barangay text,
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    is_local boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    age_group zippo.age_group NOT NULL,
    gender zippo.gender_code NOT NULL,
    barangay text NOT NULL,
    budget_range zippo.budget_range NOT NULL,
    preferred_occasions text[] NOT NULL DEFAULT '{}'::text[],
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    created_at date NOT NULL DEFAULT current_date,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id integer REFERENCES zippo.vendors(vendor_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    name text NOT NULL,
    description text,
    category zippo.product_category NOT NULL,
    price numeric(10, 2) NOT NULL CHECK (price >= 0),
    occasion_tags text[] NOT NULL DEFAULT '{}'::text[],
    recipient_tags text[] NOT NULL DEFAULT '{}'::text[],
    tags text[] NOT NULL DEFAULT '{}'::text[],
    delivery_zones text[] NOT NULL DEFAULT '{}'::text[],
    local_vendor boolean NOT NULL DEFAULT true,
    avg_rating numeric(2, 1) CHECK (avg_rating IS NULL OR avg_rating BETWEEN 1.0 AND 5.0),
    stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
    vendor_name text NOT NULL,
    popularity_score double precision NOT NULL DEFAULT 0 CHECK (popularity_score BETWEEN 0 AND 1),
    weight_score double precision NOT NULL DEFAULT 0 CHECK (weight_score BETWEEN 0 AND 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.orders (
    order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES zippo.users(user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    occasion text NOT NULL,
    recipient_type text NOT NULL,
    rating smallint CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    order_date date NOT NULL DEFAULT current_date,
    total_price numeric(10, 2) NOT NULL CHECK (total_price >= 0),
    status zippo.order_status NOT NULL DEFAULT 'completed',
    priority smallint NOT NULL DEFAULT 0 CHECK (priority BETWEEN 0 AND 10),
    promised_minutes integer NOT NULL DEFAULT 60 CHECK (promised_minutes > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.riders (
    rider_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_name text NOT NULL,
    barangay text,
    current_lat double precision NOT NULL CHECK (current_lat BETWEEN -90 AND 90),
    current_lng double precision NOT NULL CHECK (current_lng BETWEEN -180 AND 180),
    capacity integer NOT NULL DEFAULT 3 CHECK (capacity > 0),
    speed_kmph numeric(5, 2) NOT NULL DEFAULT 22.00 CHECK (speed_kmph > 0),
    average_rating numeric(2, 1) CHECK (average_rating IS NULL OR average_rating BETWEEN 1.0 AND 5.0),
    available boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.deliveries (
    delivery_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES zippo.orders(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    rider_id integer REFERENCES zippo.riders(rider_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    barangay text NOT NULL,
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    time_slot zippo.delivery_time_slot NOT NULL,
    distance_km numeric(5, 2) NOT NULL CHECK (distance_km >= 0),
    assigned_at timestamptz NOT NULL DEFAULT now(),
    status zippo.delivery_status NOT NULL DEFAULT 'delivered',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- MODULE 1: GIFT INTELLIGENCE FILTER STORAGE
-- =========================

CREATE TABLE IF NOT EXISTS zippo.gift_filter_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id integer REFERENCES zippo.users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    occasion text,
    recipient_type text,
    budget_min numeric(10, 2) CHECK (budget_min IS NULL OR budget_min >= 0),
    budget_max numeric(10, 2) CHECK (budget_max IS NULL OR budget_max >= 0),
    location_text text,
    preferences text[] NOT NULL DEFAULT '{}'::text[],
    avoid_terms text[] NOT NULL DEFAULT '{}'::text[],
    strict_budget boolean NOT NULL DEFAULT true,
    require_stock boolean NOT NULL DEFAULT true,
    require_delivery_zone boolean NOT NULL DEFAULT false,
    min_rating numeric(2, 1) CHECK (min_rating IS NULL OR min_rating BETWEEN 1.0 AND 5.0),
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max)
);

CREATE TABLE IF NOT EXISTS zippo.gift_filter_results (
    run_id uuid NOT NULL REFERENCES zippo.gift_filter_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    result_rank integer NOT NULL CHECK (result_rank > 0),
    score double precision NOT NULL CHECK (score BETWEEN 0 AND 1),
    score_parts jsonb NOT NULL DEFAULT '{}'::jsonb,
    passed_filter boolean NOT NULL DEFAULT true,
    filter_reasons text[] NOT NULL DEFAULT '{}'::text[],
    explanation text[] NOT NULL DEFAULT '{}'::text[],
    method text NOT NULL DEFAULT 'gift_intelligence_filter',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, product_id),
    UNIQUE (run_id, result_rank)
);

-- =========================
-- MODULE 2: CONTENT-BASED FILTERING / CBF STORAGE
-- =========================

CREATE TABLE IF NOT EXISTS zippo.product_cbf_profiles (
    product_id integer PRIMARY KEY REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    profile_text text NOT NULL DEFAULT '',
    term_weights jsonb NOT NULL DEFAULT '{}'::jsonb,
    vocabulary_version text NOT NULL DEFAULT 'v1',
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.recommendation_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id integer REFERENCES zippo.users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    seed_product_id integer REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    query_text text,
    occasion text,
    recipient_type text,
    budget_max numeric(10, 2) CHECK (budget_max IS NULL OR budget_max >= 0),
    preferences text[] NOT NULL DEFAULT '{}'::text[],
    candidate_product_ids integer[] NOT NULL DEFAULT '{}'::integer[],
    min_df integer NOT NULL DEFAULT 1 CHECK (min_df > 0),
    config jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.recommendation_results (
    run_id uuid NOT NULL REFERENCES zippo.recommendation_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    result_rank integer NOT NULL CHECK (result_rank > 0),
    similarity double precision NOT NULL CHECK (similarity BETWEEN 0 AND 1),
    recommendation_score double precision NOT NULL CHECK (recommendation_score BETWEEN 0 AND 1),
    final_score double precision CHECK (final_score IS NULL OR final_score BETWEEN 0 AND 1),
    matched_terms text[] NOT NULL DEFAULT '{}'::text[],
    method text NOT NULL DEFAULT 'content_based_filtering',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, product_id),
    UNIQUE (run_id, result_rank)
);

-- =========================
-- MODULE 3: DELIVERY OPTIMIZER STORAGE
-- =========================

CREATE TABLE IF NOT EXISTS zippo.delivery_optimizer_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    traffic_multiplier numeric(4, 2) NOT NULL DEFAULT 1.15 CHECK (traffic_multiplier > 0),
    settings jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    method text NOT NULL DEFAULT 'greedy_delivery_optimizer'
);

CREATE TABLE IF NOT EXISTS zippo.delivery_assignments (
    assignment_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL REFERENCES zippo.delivery_optimizer_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    rider_id integer REFERENCES zippo.riders(rider_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    total_distance_km numeric(7, 3) NOT NULL DEFAULT 0 CHECK (total_distance_km >= 0),
    estimated_total_minutes numeric(7, 2) NOT NULL DEFAULT 0 CHECK (estimated_total_minutes >= 0),
    status zippo.assignment_status NOT NULL DEFAULT 'assigned',
    method text NOT NULL DEFAULT 'greedy_delivery_optimizer',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.delivery_assignment_stops (
    stop_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id uuid NOT NULL REFERENCES zippo.delivery_assignments(assignment_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    order_id integer NOT NULL REFERENCES zippo.orders(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    sequence_no integer NOT NULL CHECK (sequence_no > 0),
    action zippo.route_stop_action NOT NULL,
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    distance_from_previous_km numeric(7, 3) NOT NULL DEFAULT 0 CHECK (distance_from_previous_km >= 0),
    estimated_minutes_from_previous numeric(7, 2) NOT NULL DEFAULT 0 CHECK (estimated_minutes_from_previous >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (assignment_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS zippo.delivery_unassigned_orders (
    run_id uuid NOT NULL REFERENCES zippo.delivery_optimizer_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    order_id integer NOT NULL REFERENCES zippo.orders(order_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    reason text NOT NULL DEFAULT 'rider_capacity_reached',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, order_id)
);

-- =========================
-- BASELINE MODULE STORAGE
-- =========================

CREATE TABLE IF NOT EXISTS zippo.baseline_runs (
    run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id integer REFERENCES zippo.users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    query jsonb NOT NULL DEFAULT '{}'::jsonb,
    top_k integer NOT NULL DEFAULT 10 CHECK (top_k > 0),
    method text NOT NULL DEFAULT 'baseline_filter_plus_baseline_assign',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.baseline_gift_results (
    run_id uuid NOT NULL REFERENCES zippo.baseline_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    product_id integer NOT NULL REFERENCES zippo.products(product_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    result_rank integer NOT NULL CHECK (result_rank > 0),
    baseline_score double precision NOT NULL CHECK (baseline_score >= 0),
    passed_filter boolean NOT NULL DEFAULT true,
    explanation text[] NOT NULL DEFAULT '{}'::text[],
    method text NOT NULL DEFAULT 'baseline_filter',
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, product_id),
    UNIQUE (run_id, result_rank)
);

CREATE TABLE IF NOT EXISTS zippo.baseline_delivery_results (
    baseline_delivery_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id uuid NOT NULL REFERENCES zippo.baseline_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    order_id integer REFERENCES zippo.orders(order_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    rider_id integer REFERENCES zippo.riders(rider_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    distance_to_pickup_km numeric(7, 3) CHECK (distance_to_pickup_km IS NULL OR distance_to_pickup_km >= 0),
    direct_delivery_distance_km numeric(7, 3) CHECK (direct_delivery_distance_km IS NULL OR direct_delivery_distance_km >= 0),
    estimated_total_distance_km numeric(7, 3) CHECK (estimated_total_distance_km IS NULL OR estimated_total_distance_km >= 0),
    estimated_minutes numeric(7, 2) CHECK (estimated_minutes IS NULL OR estimated_minutes >= 0),
    status zippo.assignment_status NOT NULL DEFAULT 'assigned',
    method text NOT NULL DEFAULT 'baseline_nearest_rider',
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS zippo.model_run_comparisons (
    comparison_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    baseline_run_id uuid REFERENCES zippo.baseline_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    gift_filter_run_id uuid REFERENCES zippo.gift_filter_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    recommendation_run_id uuid REFERENCES zippo.recommendation_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    delivery_optimizer_run_id uuid REFERENCES zippo.delivery_optimizer_runs(run_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- =========================
-- PYTHON-COMPATIBLE VIEWS
-- These expose database rows using the dictionary keys expected by the Python modules.
-- =========================

CREATE OR REPLACE VIEW zippo.v_gifts_for_python AS
SELECT
    p.product_id AS id,
    p.name,
    p.description,
    p.price::double precision AS price,
    p.category::text AS category,
    p.vendor_id,
    p.vendor_name,
    p.stock,
    p.avg_rating::double precision AS rating,
    p.popularity_score AS popularity,
    p.local_vendor AS local,
    p.tags,
    p.occasion_tags AS occasions,
    p.recipient_tags AS recipients,
    p.delivery_zones,
    p.weight_score
FROM zippo.products p;

CREATE OR REPLACE VIEW zippo.v_riders_for_python AS
SELECT
    r.rider_id AS id,
    r.rider_name AS name,
    r.current_lat,
    r.current_lng,
    r.capacity,
    r.speed_kmph::double precision AS speed_kmph,
    r.average_rating::double precision AS average_rating,
    r.available
FROM zippo.riders r;

CREATE OR REPLACE VIEW zippo.v_orders_for_delivery_optimizer AS
SELECT
    o.order_id AS id,
    p.vendor_id,
    v.lat AS pickup_lat,
    v.lng AS pickup_lng,
    u.lat AS dropoff_lat,
    u.lng AS dropoff_lng,
    o.priority,
    o.promised_minutes,
    o.occasion,
    o.recipient_type,
    u.barangay AS dropoff_barangay,
    p.product_id,
    p.name AS product_name
FROM zippo.orders o
JOIN zippo.users u ON u.user_id = o.user_id
JOIN zippo.products p ON p.product_id = o.product_id
LEFT JOIN zippo.vendors v ON v.vendor_id = p.vendor_id
WHERE
    o.status IN ('pending', 'paid', 'processing')
    AND v.lat IS NOT NULL
    AND v.lng IS NOT NULL;

-- =========================
-- ROW LEVEL SECURITY (RLS)
-- =========================

ALTER TABLE zippo.vendors ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.riders ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.gift_filter_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.gift_filter_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.product_cbf_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.recommendation_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.recommendation_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.delivery_optimizer_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.delivery_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.delivery_assignment_stops ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.delivery_unassigned_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.baseline_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.baseline_gift_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.baseline_delivery_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE zippo.model_run_comparisons ENABLE ROW LEVEL SECURITY;

CREATE POLICY vendors_read ON zippo.vendors
    FOR SELECT TO authenticated USING (true);
CREATE POLICY vendors_insert ON zippo.vendors
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY vendors_update ON zippo.vendors
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY vendors_delete ON zippo.vendors
    FOR DELETE TO authenticated USING (true);

CREATE POLICY users_read ON zippo.users
    FOR SELECT TO authenticated USING (true);
CREATE POLICY users_insert ON zippo.users
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY users_update ON zippo.users
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY users_delete ON zippo.users
    FOR DELETE TO authenticated USING (true);

CREATE POLICY products_read ON zippo.products
    FOR SELECT TO authenticated USING (true);
CREATE POLICY products_insert ON zippo.products
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY products_update ON zippo.products
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY products_delete ON zippo.products
    FOR DELETE TO authenticated USING (true);

CREATE POLICY orders_read ON zippo.orders
    FOR SELECT TO authenticated USING (true);
CREATE POLICY orders_insert ON zippo.orders
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY orders_update ON zippo.orders
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY orders_delete ON zippo.orders
    FOR DELETE TO authenticated USING (true);

CREATE POLICY riders_read ON zippo.riders
    FOR SELECT TO authenticated USING (true);
CREATE POLICY riders_insert ON zippo.riders
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY riders_update ON zippo.riders
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY riders_delete ON zippo.riders
    FOR DELETE TO authenticated USING (true);

CREATE POLICY deliveries_read ON zippo.deliveries
    FOR SELECT TO authenticated USING (true);
CREATE POLICY deliveries_insert ON zippo.deliveries
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY deliveries_update ON zippo.deliveries
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY deliveries_delete ON zippo.deliveries
    FOR DELETE TO authenticated USING (true);

CREATE POLICY gift_filter_runs_read ON zippo.gift_filter_runs
    FOR SELECT TO authenticated USING (true);
CREATE POLICY gift_filter_runs_insert ON zippo.gift_filter_runs
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY gift_filter_runs_update ON zippo.gift_filter_runs
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY gift_filter_runs_delete ON zippo.gift_filter_runs
    FOR DELETE TO authenticated USING (true);

CREATE POLICY gift_filter_results_read ON zippo.gift_filter_results
    FOR SELECT TO authenticated USING (true);
CREATE POLICY gift_filter_results_insert ON zippo.gift_filter_results
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY gift_filter_results_update ON zippo.gift_filter_results
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY gift_filter_results_delete ON zippo.gift_filter_results
    FOR DELETE TO authenticated USING (true);

CREATE POLICY product_cbf_profiles_read ON zippo.product_cbf_profiles
    FOR SELECT TO authenticated USING (true);
CREATE POLICY product_cbf_profiles_insert ON zippo.product_cbf_profiles
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY product_cbf_profiles_update ON zippo.product_cbf_profiles
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY product_cbf_profiles_delete ON zippo.product_cbf_profiles
    FOR DELETE TO authenticated USING (true);

CREATE POLICY recommendation_runs_read ON zippo.recommendation_runs
    FOR SELECT TO authenticated USING (true);
CREATE POLICY recommendation_runs_insert ON zippo.recommendation_runs
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY recommendation_runs_update ON zippo.recommendation_runs
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY recommendation_runs_delete ON zippo.recommendation_runs
    FOR DELETE TO authenticated USING (true);

CREATE POLICY recommendation_results_read ON zippo.recommendation_results
    FOR SELECT TO authenticated USING (true);
CREATE POLICY recommendation_results_insert ON zippo.recommendation_results
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY recommendation_results_update ON zippo.recommendation_results
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY recommendation_results_delete ON zippo.recommendation_results
    FOR DELETE TO authenticated USING (true);

CREATE POLICY delivery_optimizer_runs_read ON zippo.delivery_optimizer_runs
    FOR SELECT TO authenticated USING (true);
CREATE POLICY delivery_optimizer_runs_insert ON zippo.delivery_optimizer_runs
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY delivery_optimizer_runs_update ON zippo.delivery_optimizer_runs
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY delivery_optimizer_runs_delete ON zippo.delivery_optimizer_runs
    FOR DELETE TO authenticated USING (true);

CREATE POLICY delivery_assignments_read ON zippo.delivery_assignments
    FOR SELECT TO authenticated USING (true);
CREATE POLICY delivery_assignments_insert ON zippo.delivery_assignments
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY delivery_assignments_update ON zippo.delivery_assignments
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY delivery_assignments_delete ON zippo.delivery_assignments
    FOR DELETE TO authenticated USING (true);

CREATE POLICY delivery_assignment_stops_read ON zippo.delivery_assignment_stops
    FOR SELECT TO authenticated USING (true);
CREATE POLICY delivery_assignment_stops_insert ON zippo.delivery_assignment_stops
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY delivery_assignment_stops_update ON zippo.delivery_assignment_stops
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY delivery_assignment_stops_delete ON zippo.delivery_assignment_stops
    FOR DELETE TO authenticated USING (true);

CREATE POLICY delivery_unassigned_orders_read ON zippo.delivery_unassigned_orders
    FOR SELECT TO authenticated USING (true);
CREATE POLICY delivery_unassigned_orders_insert ON zippo.delivery_unassigned_orders
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY delivery_unassigned_orders_update ON zippo.delivery_unassigned_orders
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY delivery_unassigned_orders_delete ON zippo.delivery_unassigned_orders
    FOR DELETE TO authenticated USING (true);

CREATE POLICY baseline_runs_read ON zippo.baseline_runs
    FOR SELECT TO authenticated USING (true);
CREATE POLICY baseline_runs_insert ON zippo.baseline_runs
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY baseline_runs_update ON zippo.baseline_runs
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY baseline_runs_delete ON zippo.baseline_runs
    FOR DELETE TO authenticated USING (true);

CREATE POLICY baseline_gift_results_read ON zippo.baseline_gift_results
    FOR SELECT TO authenticated USING (true);
CREATE POLICY baseline_gift_results_insert ON zippo.baseline_gift_results
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY baseline_gift_results_update ON zippo.baseline_gift_results
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY baseline_gift_results_delete ON zippo.baseline_gift_results
    FOR DELETE TO authenticated USING (true);

CREATE POLICY baseline_delivery_results_read ON zippo.baseline_delivery_results
    FOR SELECT TO authenticated USING (true);
CREATE POLICY baseline_delivery_results_insert ON zippo.baseline_delivery_results
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY baseline_delivery_results_update ON zippo.baseline_delivery_results
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY baseline_delivery_results_delete ON zippo.baseline_delivery_results
    FOR DELETE TO authenticated USING (true);

CREATE POLICY model_run_comparisons_read ON zippo.model_run_comparisons
    FOR SELECT TO authenticated USING (true);
CREATE POLICY model_run_comparisons_insert ON zippo.model_run_comparisons
    FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY model_run_comparisons_update ON zippo.model_run_comparisons
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY model_run_comparisons_delete ON zippo.model_run_comparisons
    FOR DELETE TO authenticated USING (true);

-- =========================
-- INDEXES
-- =========================

CREATE INDEX IF NOT EXISTS idx_users_barangay ON zippo.users (barangay);
CREATE INDEX IF NOT EXISTS idx_users_budget_range ON zippo.users (budget_range);
CREATE INDEX IF NOT EXISTS idx_users_preferred_occasions ON zippo.users USING gin (preferred_occasions);

CREATE INDEX IF NOT EXISTS idx_vendors_barangay ON zippo.vendors (barangay);
CREATE INDEX IF NOT EXISTS idx_products_vendor_id ON zippo.products (vendor_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON zippo.products (category);
CREATE INDEX IF NOT EXISTS idx_products_price ON zippo.products (price);
CREATE INDEX IF NOT EXISTS idx_products_stock ON zippo.products (stock);
CREATE INDEX IF NOT EXISTS idx_products_local_vendor ON zippo.products (local_vendor);
CREATE INDEX IF NOT EXISTS idx_products_occasion_tags ON zippo.products USING gin (occasion_tags);
CREATE INDEX IF NOT EXISTS idx_products_recipient_tags ON zippo.products USING gin (recipient_tags);
CREATE INDEX IF NOT EXISTS idx_products_tags ON zippo.products USING gin (tags);
CREATE INDEX IF NOT EXISTS idx_products_delivery_zones ON zippo.products USING gin (delivery_zones);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON zippo.orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_product_id ON zippo.orders (product_id);
CREATE INDEX IF NOT EXISTS idx_orders_order_date ON zippo.orders (order_date);
CREATE INDEX IF NOT EXISTS idx_orders_status ON zippo.orders (status);

CREATE INDEX IF NOT EXISTS idx_riders_available ON zippo.riders (available);
CREATE INDEX IF NOT EXISTS idx_deliveries_order_id ON zippo.deliveries (order_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_rider_id ON zippo.deliveries (rider_id);
CREATE INDEX IF NOT EXISTS idx_deliveries_barangay ON zippo.deliveries (barangay);
CREATE INDEX IF NOT EXISTS idx_deliveries_time_slot ON zippo.deliveries (time_slot);
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON zippo.deliveries (status);

CREATE INDEX IF NOT EXISTS idx_gift_filter_results_run_rank ON zippo.gift_filter_results (run_id, result_rank);
CREATE INDEX IF NOT EXISTS idx_recommendation_results_run_rank ON zippo.recommendation_results (run_id, result_rank);
CREATE INDEX IF NOT EXISTS idx_delivery_assignments_run_id ON zippo.delivery_assignments (run_id);
CREATE INDEX IF NOT EXISTS idx_delivery_assignment_stops_assignment_id ON zippo.delivery_assignment_stops (assignment_id);
CREATE INDEX IF NOT EXISTS idx_baseline_gift_results_run_rank ON zippo.baseline_gift_results (run_id, result_rank);
CREATE INDEX IF NOT EXISTS idx_baseline_delivery_results_run_id ON zippo.baseline_delivery_results (run_id);

-- =========================
-- UPDATED_AT TRIGGERS
-- =========================

DROP TRIGGER IF EXISTS trg_vendors_updated_at ON zippo.vendors;
CREATE TRIGGER trg_vendors_updated_at
BEFORE UPDATE ON zippo.vendors
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_users_updated_at ON zippo.users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON zippo.users
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_products_updated_at ON zippo.products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON zippo.products
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_orders_updated_at ON zippo.orders;
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON zippo.orders
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_riders_updated_at ON zippo.riders;
CREATE TRIGGER trg_riders_updated_at
BEFORE UPDATE ON zippo.riders
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

DROP TRIGGER IF EXISTS trg_deliveries_updated_at ON zippo.deliveries;
CREATE TRIGGER trg_deliveries_updated_at
BEFORE UPDATE ON zippo.deliveries
FOR EACH ROW EXECUTE FUNCTION zippo.set_updated_at();

-- =========================
-- SUPABASE NOTES
-- =========================
-- This schema uses zippo.* instead of public.* to avoid clashing with auth.users.
-- In Supabase client code, query with:
--   supabase.schema('zippo').from('products').select('*')
-- Or expose the zippo schema in Project Settings -> API -> Exposed schemas.
--
-- RLS is enabled with permissive authenticated policies. Tighten as needed.

COMMIT;
